[package]
name = "biwa"
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
repository = "https://github.com/risu729/biwa"
license = "MIT"
include = ["/README.md", "/src/**/*.rs"]
description = "CLI to execute commands on UNSW CSE servers from local"
keywords = ["unsw"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "=4.5.53", features = ["derive"] }
color-eyre = "=0.6.5"
eyre = "=0.6.12"
itertools = "=0.14.0"
tokio = { version = "=1.47.1", features = ["full"] }
tracing = "=0.1.44"
tracing-subscriber = "=0.3.22"

[profile.dist]
inherits = "release"
lto = "thin"
