[package]
name = "biwa"
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
repository = "https://github.com/risu729/biwa"
license = "MIT"
include = ["/README.md", "/src/**/*.rs"]
description = "CLI to execute commands on UNSW CSE servers from local"
keywords = ["unsw"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "=4.5.59", features = ["derive"] }
color-eyre = "=0.6.5"
eyre = "=0.6.12"
figment = { version = "0.10.19", features = ["toml", "json", "yaml", "env"] }
itertools = "=0.14.0"
json5 = "1.3.1"
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = { version = "0.27", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "=1.49.0", features = ["full"] }
toml = "1.0.3"
tracing = "=0.1.44"
tracing-subscriber = "=0.3.22"
usage-lib = { version = "2", features = ["clap", "docs"] }
duct = "1.1.1"

[profile.dist]
inherits = "release"
lto = "thin"

[dev-dependencies]
insta = { version = "1.46.3", features = ["json"] }
pretty_assertions = "1.4.1"
rstest = "0.26.1"
tempfile = "3.25.0"
