# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
rust = { version = "1.93.1", profile = "default" }
"aqua:EmbarkStudios/cargo-deny" = "0.19.0"
actionlint = "1.7.10"
# used in actionlint
shellcheck = "0.11.0"
ghalint = "1.5.5"
pinact = "3.9.0"
zizmor = "1.12.1"
# required for pipx backend
uv = "0.10.2"
yamllint = "1.38.0"
typos = "1.43.4"
"aqua:release-plz/release-plz" = "0.3.147"
"aqua:axodotdev/cargo-dist" = "0.30.3"
bun = "1.3.9"
"npm:oxfmt" = "0.32.0"

[settings]
experimental = true

[env]
'_'.path = ["target/debug/"]

[task_config]
includes = ["tasks.toml"]

[prepare.bun_docs]
auto = true
dir = "docs"
sources = ["docs/bun.lock", "docs/package.json"]
outputs = ["docs/node_modules"]
run = "bun install --frozen-lockfile"
