# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
rust = { version = "1.93.0", profile = "default" }
"aqua:EmbarkStudios/cargo-deny" = "0.19.0"
actionlint = "1.7.10"
# used in actionlint
shellcheck = "0.11.0"
ghalint = "1.5.5"
pinact = "3.8.0"
zizmor = "1.12.1"
taplo = "0.10.0"
yamlfmt = "0.21.0"
# required for pipx backend
uv = "0.9.26"
yamllint = "1.38.0"
typos = "1.42.2"
"aqua:release-plz/release-plz" = "0.3.147"
"aqua:axodotdev/cargo-dist" = "0.30.3"

[settings]
experimental = true

[env]
'_'.path = ["target/debug/"]

[task_config]
includes = ["tasks.toml"]
