# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
rust = { version = "1.91.1", profile = "default" }
"aqua:EmbarkStudios/cargo-deny" = "0.18.5"
actionlint = "1.7.9"
# used in actionlint
shellcheck = "0.11.0"
ghalint = "1.5.3"
pinact = "3.4.4"
zizmor = "1.12.1"
taplo = "0.10.0"
yamlfmt = "0.20.0"
# required for pipx backend
uv = "0.9.11"
yamllint = "1.37.1"
typos = "1.39.2"
"aqua:release-plz/release-plz" = "0.3.147"
"aqua:axodotdev/cargo-dist" = "0.30.2"

[settings]
experimental = true

[env]
'_'.path = ["target/debug/"]

[task_config]
includes = ["tasks.toml"]
