name: release-plz

on:
  push:
    branches:
      - main

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  release-pr:
    name: Create Release PR
    if: github.repository_owner == 'risu729'
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read # for checkout
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2026.1.11
          # cache doesn't work well with rust
          cache: false

      - name: Create biwa-bot GitHub App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: github-app
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write # for updating branches
          permission-pull-requests: write # for creating PRs

      - name: Create release-plz PR
        run: release-plz release-pr
        env:
          GIT_TOKEN: ${{ steps.github-app.outputs.token }}

  release:
    name: Release
    if: github.repository_owner == 'risu729'
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read # for checkout
      id-token: write # for trusted publishing
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2026.1.11
          # cache doesn't work well with rust
          cache: false

      - name: Create biwa-bot GitHub App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: github-app
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write # for creating tags

      - name: Release
        run: release-plz release
        env:
          GIT_TOKEN: ${{ steps.github-app.outputs.token }}
          # TODO: use trusted publishing after first release
          # ref: https://crates.io/docs/trusted-publishing
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  actions-timeline:
    name: Generate Actions Timeline
    needs:
      - release-pr
      - release
    if: ${{ !cancelled() }}

    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      actions: read

    steps:
      - name: actions-timeline
        uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2.2.6
